### ISSUE TITLE
Images saved in tabs order

### ISSUE THREAD

**Issue by lapega** [mcdamo/tab-image-saver#13]
It is possible to save the images in the same order the tabs are open?
Or the option to use part of the url as the image name?

Thank you in advance!

**Comment by mcdamo** [comment]
I think this could be much slower because it would require waiting for each tab to download and save before requesting the next tab, instead of downloading tabs in parallel.

**Comment by lapega** [comment]
Thank you anyway!

I've tried another extension that do the job: [Download Images from Tabs](https://github.com/famousRobot9000/Download-Images-From-Tabs)

**Comment by mcdamo** [comment]
I just realise what you probably want is the images to be saved with sequential filenames in the same order as the tabs, rather than **downloading** in any specific order.

**Comment by lapega** [comment]
Yep!

> It is possible to save the images in the same order the tabs are open?

**Comment by mcdamo** [comment]
This is now feasible, just need to create preferences for defining the file naming scheme.

**Comment by lapega** [comment]
Ha! Excelent. Thank you a lot!

**Comment by mcdamo** [comment]
The 'index' keyword in [Path rules](/mcdamo/tab-image-saver/#path-rules) preference allows for this feature. Included in v2.2+
