### ISSUE TITLE
Detect duplicate (skip on already existent file)

### ISSUE THREAD

**Issue by Micha-MHX** [mcdamo/tab-image-saver#15]
Barracuda Image Saver+ (down not work with FF57+) has the feature to detect duplicates (based on hash value).

If already downloaded / identical file exists, then skip downloading instead of renaming or overwriting.

Even if no hash value will be made, then please only add the option to skip downlad as third option to available "rename" and "overwrite".

Thank you.

**Comment by mcdamo** [comment]
I don't believe the [WebExtensions API](https://wiki.mozilla.org/WebExtensions/Filesystem) has yet any method to list or read files in the downloads directory so it is not possible to detect if files already exist on the filesystem.

It could be possible to keep a log of all downloads using [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) and having the option to skip downloads with matching url, or skip saving files with matching hash.

**Comment by AntoineTurmel** [comment]
You can use ```conflictActionOptional``` but it's only for filename see:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download

The IndexedDB could be good, but it would be big at the end and could have some privacy issues.

**Comment by mcdamo** [comment]
This addon does use `conflictAction` when saving files but the options are limited and I don't believe that addresses this issue of detecting duplicates.

**Comment by mcdamo** [comment]
Addon access to filesystem is not supported by Firefox, closing.
