### ISSUE TITLE
Not working with Pixiv

### ISSUE THREAD

**Issue by sergiocornaga** [mcdamo/tab-image-saver#17]
I've noticed this add-on is unable to save images from pixiv.net, instead saving empty files with the same filename. This is a behaviour I've noticed in Firefox itself too, where dragging a Pixiv image into a folder to save it creates an empty file, while right clicking and saving it succeeds. I think you have to make a free account to access full resolution images on the site, but you can still see lower resolution images failing to save without doing this. Here are a couple of example links if wanted:
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=22014425
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=21991924

**Comment by mcdamo** [comment]
Does this happen when you are logged in to a Pixiv account? I notice with guest access it is difficult to save the images, getting 403 error without using the addon.

**Comment by sergiocornaga** [comment]
Yep, happens both when logged in and when not. I think there's something in place to avoid hotlinking, so images are only supposed to load when you've visited the page where they're supposed to display. I haven't investigated thoroughly, but I'm beginning to wonder if addressing this for the addon is really worth the effort!

**Comment by mcdamo** [comment]
Testing while logged in to a Pixiv account has been successful for me. Make sure you are not using the "Incognito mode" in the addon options.

**Comment by mcdamo** [comment]
Pixiv implements strong protections against saving images as a guest, but with a free account this addon appears to work well.
