### ISSUE TITLE
Custom name file

### ISSUE THREAD

**Issue by AntoineTurmel** [mcdamo/tab-image-saver#2]
Some website doesn't provide good file name in the URL example with 500px:

https://drscdn.500px.org/photo/113791545/q%3D80_m%3D2000/v2?user_id=13376435&webp=true&sig=4a16c4eeb21c9eb9ab9f780b69b293b50dc5d62c4d2f38df98a79caf9bf775e4

It will be saved as "v2?user_id=13376435&webp=true&sig=4a16c4eeb21c9eb9ab9f780b69b293b50dc5d62c4d2f38df98a79caf9bf775e4" while the page title is "stock-photo-113791545.jpg"

So I guess it would be nice to have a white list that use Page title instead of the URL for the file name.

**Comment by mcdamo** [comment]
Please try new v1.1.2, it should handle this url better now.

**Comment by AntoineTurmel** [comment]
It's working great, thanks !
