### ISSUE TITLE
Filenames include URL-encoding symbols (eg. %20)

### ISSUE THREAD

**Issue by b923242** [mcdamo/tab-image-saver#21]
For example: with normal firefox save
yande.re 468966 animal_ears areola ass benghuai_xueyuan bunny_ears erect_nipples higandgk naked_ribbon yae_sakura_(benghuai_xueyuan)
With add-on:
yande.re%20468966%20animal_ears%20areola%20ass%20benghuai_xueyuan%20bunny_ears%20erect_nipples%20higandgk%20naked_ribbon%20yae_sakura_%28benghuai_xueyuan%29

This only happen in 2.2.1

**Comment by mcdamo** [comment]
Thankyou for reporting this, it is fixed in v2.2.2
