### ISSUE TITLE
Error reloading discarded tabs with illegal URLs

### ISSUE THREAD

**Issue by AntoineTurmel** [mcdamo/tab-image-saver#25]
When I quit Firefox, I use the session restore feature... and I have noticed issues using Tab Image Saver:
- Having "about:" tabs unloaded cause errors like this when I press the Tab Image Saver button:
```waitForTabs Error: "Illegal URL: about:newtab"```
- I tend to have lot of unloaded tabs when opening Firefox, it would be nice to have an option to just skip "unloaded" tabs instead of reloading them.

You can easily reproduce the first issue by:
1. Opening a few tabs including about:newtab, about:preferences
2. Enable restore previous session option from Firefox
3. Quit Firefox with about: tabs opened
4. Start Firefox
5. Load a picture URL
6. Press Tab Image Saver button.
7. You will get the error in debugger

For now I was keeping version 1.3.0 because it would work flawless and quicker, but I figure I would help improve the add-on which has cool features and as I'm a webext developer as well.

**Comment by mcdamo** [comment]
I think a filter on tab URLs is the best way to solve this error. Only tabs with http[s] or ftp[s] will be processed.

**Comment by mcdamo** [comment]
New release v2.3.0 should have resolved the issue of illegal URLs.
