### ISSUE TITLE
Option to skip discarded/unloaded tabs

### ISSUE THREAD

**Issue by mcdamo** [mcdamo/tab-image-saver#26]
I tend to have lot of unloaded tabs when opening Firefox, it would be nice to have an option to just skip "unloaded" tabs instead of reloading them. I think version 1.3.0 skip those tabs because it's way quicker !

_Originally posted by @AntoineTurmel in https://github.com/mcdamo/tab-image-saver/issues/25#issuecomment-421516037_

**Comment by mcdamo** [comment]
@AntoineTurmel can you give some background or example when you would want the addon to skip discarded tabs?

**Comment by AntoineTurmel** [comment]
Well as I said, I mostly use Firefox without starting new session, so when I quit Firefox and reopen it later, It keeps all my previous tabs in an « unloaded » state. The problem is Tab Image Saver is reloading each tabs (even if it's not Image tabs) to check for pictures... I just want Tab Image Saver to check for « loaded » tabs only.

**Comment by mcdamo** [comment]
So you would run the addon across a range of tabs and you already know that your tabs from a previous session do not have images - is that why you are happy for it to ignore these tabs? 

I get that some of your tabs are in a discarded state and reloading the tabs takes time, but I would like to better understand why you would run the addon on a set of tabs, for example all tabs to the right, and be satisfied when it skips over tabs in this set.

**Comment by AntoineTurmel** [comment]
That would be a part of the solution... but I use to open tabs in left and right position of my previous session ^^ and it used to work good with version 1.3.0

**Comment by mcdamo** [comment]
The option to ignore discarded tabs is added in v2.4.0

**Comment by AntoineTurmel** [comment]
Thanks a lot :)

**Comment by AntoineTurmel** [comment]
@mcdamo since 3.0 the checkbox is unchecked and I can't enabled it...
