### ISSUE TITLE
Active tab not downloading image

### ISSUE THREAD

**Issue by dgreen97** [mcdamo/tab-image-saver#31]
Ever since the update, the active tab doesn't get included when downloading images. I like to have the active tab selected and then get all images to the right of it as well to make icons with. Here are my settings:

![example](https://user-images.githubusercontent.com/3385778/46559367-c08e7f00-c8b5-11e8-9a28-3355979bc51f.jpg)

So I'll have like 9 tabs open with images and it grabs the other 8 but not the one in the active tab.

**Comment by dgreen97** [comment]
No thats what I havew selected "Tabs to include: Acvtive Tab". I'll test
that today with selecting the image to the right of the active tab and see
if that active tab gets saved. This is happening on sites like
costumesupercenter.com. I work on 13 party sites and I have to save like
9-10 images at once to make icons for party supplies so thats where Im
using it

**Comment by mcdamo** [comment]
To test I would need the full url to the page that has the issue, not just the domain name.
Or if you are inclined you can download the addon source and load it using Firefox's "Load Temporary Add-on", then the addon will display debugging information in the browser console.

**Comment by mcdamo** [comment]
Unable to replicate, no response from user.
