### ISSUE TITLE
Add "last saved folder" instead of bulk download directory

### ISSUE THREAD

**Issue by Shilar** [mcdamo/tab-image-saver#34]
A feature I missed in the upgrade to 57 was from an extension similar to yours. It had three download options: To the Download folder, to the previously saved directory, and custom. Bascially, I'd like to open and save one pic, and then bulk save the rest to the same folder.

**Comment by mcdamo** [comment]
This would only work if your last saved destination was in your download folder. This is because webextensions can only save within the default downloads folder.

**Comment by mcdamo** [comment]
Webextensions cannot save automatically outside of the default download folder so this could only work when the last saved path is within the default folder.

**Comment by mcdamo** [comment]
This is not practical with the way webextensions are sandboxed.
