### ISSUE TITLE
The add-on doesn't work with private browsing mode

### ISSUE THREAD

**Issue by Srolic4ever** [mcdamo/tab-image-saver#35]
Hello :)
First i want to say thanks for this extension! it's very helpful :)
But i have a problem, after the first install the program working great, but after i exit Firefox, and open the browser again the add-on is not downloading images at all, nothing.
I figured to solve this problem by - uninstalling the add-on - exit firefox - enter firefox again - install the add-on and that should work, until i exit again from the browser.

**Comment by mcdamo** [comment]
Did you find a solution, or what was causing the problem?

**Comment by Srolic4ever** [comment]
Hi :)
I found the solution, i turned on the option to remember history (after i
set it to "never save history")
Thats was the problem for me :)

**Comment by mcdamo** [comment]
Confirmed the addon breaks when Firefox **History** setting is **Never remember history**, as described above the addon only works after the initial install and breaks after restarting the browser. Will be issuing an update to rectify this.

**Comment by mcdamo** [comment]
Fixed in v2.5.0
