### ISSUE TITLE
Download images from cache?

### ISSUE THREAD

**Issue by Joethelazy1** [mcdamo/tab-image-saver#37]
Is there a way for the addon to pull images from the disk cache in Firefox? I am using ver. 64, 64bit. I have Firefox installed on a 4GB ram drive, as well as the cache. It would be awesome if it could just retrieve the images from the ram drive rather than downloading each one again, even after they have been opened in a tab and downloaded once already. 

Thanks for your time.

**Comment by mcdamo** [comment]
In my experience it uses the Firefox cache wherever possible and downloads are usually instantaneous. Perhaps a site you are using has a no-cache policy or there is something else causing this, can you give a test page that isn't using the cache?

**Comment by Joethelazy1** [comment]
Dang! You replied so fast I missed it! Thanks for that. The reason that I asked is because I weed through images from photo shoots. The guy sends a link, private of course, and then I open the page, select which pics to save, and open each one in a separate tab. The images are sent sometimes in very high resolutions, which means it takes a bit of time for each one to open. Then when I use your program to save from all the tabs, the new tab opens, and then it just downloads all of them again, taking roughly the same amount of time that it took to originally open them in each tab. I will ask about the no caching aspect, because it acts exactly like that, so you make a good point. Is there a way to find out on my end? There’s not really any sort of program involved that I know of, it’s just a webpage of thumbnails with a check box under each. I have tried moving the cache to a RAM drive successfully, but it still just re-downloads, starting with the first picture, so I don’t think it’s a case of running out of cache or something similar.

Thanks for your time, the quick response and the addon!
Joethelazy1

________________________________

**Comment by mcdamo** [comment]
You can check the cache policy with the Web Developer Network tools in the [Response headers](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_details) panel.

**Comment by mcdamo** [comment]
The addon's use of the browser cache for downloading is improved in v2.5.1, though there is no workaround for images with a no-cache policy.
