### ISSUE TITLE
Not saving pictures

### ISSUE THREAD

**Issue by derrapf** [mcdamo/tab-image-saver#38]
I have a lot of (lets say several hundred) opened tabs with pictures in it.
Every time, I press the button, I get, (depending on which tab I am)
*  no message, but also no savings
* Message: "User cancelled. Failed downloads: 1  1 Tabs do not have permisson"
So: Why are the others not saved? 
Which tab does not have permission?
At least more information would be nice to find ot why and which of the image(s) could not be downloaded.
And if one image cannot be downoaded: Why not download the others?
Ralf

**Comment by mcdamo** [comment]
Perhaps you are cancelling the addon before it is ready to begin downloading.

As of v2.4.1 the addon processes all targeted tabs before beginning the downloads, and if any tabs are still loading it will wait for them to be ready.

The message "User cancelled..." also suggests you may be cancelling the addon whilst it is still busy preparing.

I suggest you test with fewer tabs, lets say 100 or less, to confirm if this is the issue.

**Comment by Alfonsorb** [comment]
I also am having this issue. OP, where you able to solve it? 
I currently use Firefox. The addon was working fine until a few days ago but then just ran cold. It doesn't seem to be registering tabs with links.

**Comment by mcdamo** [comment]
v2.5 has improved performance and it handles 100 tabs with no problem.

**Comment by mcdamo** [comment]
Unable to reproduce error and no response from OP.
