### ISSUE TITLE
Images ending with ?xxxxx will save incorrectly.

### ISSUE THREAD

**Issue by doio** [mcdamo/tab-image-saver#4]
For example, images URL like https://www.example.com/ss17_2000x.jpg?v=1497020526 will be save into folder incorrectly with the ending ?v=1497020526 being saved.

**Comment by AntoineTurmel** [comment]
Yeah I reported the same issue on #2 it's kinda annoying. It could be solved using the page title or by renaming the file.

**Comment by mcdamo** [comment]
Please try new v1.1.2, it should handle URLs like this better.
