### ISSUE TITLE
UTF8 filenames Not Downloading

### ISSUE THREAD

**Issue by MadManMoon** [mcdamo/tab-image-saver#43]
Hi there.

I'm setup to save from tabs to the right, with a low minimum size count, everything else is pretty much stock.

It just won't download the files, no matter what I do, what am I doing wrong? Just installed, FF 67.0.4.

Have tried with both JPGs and GIFs.

Here's the site I'm trying:
`https://kittens.tistory.com/171`

Here's two of the image tab URLs that I'm attempting to download from.

1. `https://t1.daumcdn.net/cfile/tistory/99EBBC405B3047BB11?original`
2. `https://t1.daumcdn.net/cfile/tistory/999FE1405B3047BD16?original`

If you wish to test GIFs, then there's ... hm ... here's some TWICE GIFs:
`https://yesesyo.tistory.com/1352?category=677583`

I see that these image types may mirror something that some of the Firefox reviews were saying last year about parameter filenames being problematic, but it looks like that was fixed.

Could it be something to do with the language of the original filenames? (Korean)

I've just tested it on roman characters (~English) as opposed to the Hangul ones linked above, and it does work. However I can't then use this to get to HQ imagery. 🙁 

FWIW - The built in rules are renaming GIFs as JPGs for some reason, I'm just trying to learn your mini-code for that to work around it. Bit frustrating. But easily dealt with. :-)

Very Best
M_M_M

FWIW - I'm very happy about what you've made here, not posting this as an annoyance, just hoping to help shore up any issues. :-)

**Comment by mcdamo** [comment]
New release v2.5.5 should fix the issues with non-english filenames and a bug with the path rules that was causing the GIF to be saved as JPG.

**Comment by mcdamo** [comment]
Issue resolved.
