### ISSUE TITLE
SUGGESTION - Index Mask/Start/Step

### ISSUE THREAD

**Issue by MadManMoon** [mcdamo/tab-image-saver#44]
Just a suggestion (sorry, still working out how to use github after 10 years) ... basically what it says in the title/subject line.

The ability to define the filename determination to a bit more order. Meaning that let's say that I'd like to number my images perhaps not starting at the number 1. Or maybe increase in twos (for whatever weird reason), I dunno.

So, if I already know that I have 58 car pictures already in the "Cars" folder, know that I'm already using a 3 number system ###, and want to start at 59, with single digit increments, then I would put:
`Cars/car_<index-in|000,59,1><ext|xExt|xMimeExt|.jpg>`
or
`Cars/car_<index-in|###,59,1><ext|xExt|xMimeExt|.jpg>`

If you wanted to be adventurous, you might be able to also (once the logic has been defined) set a decreasing standard, too:
`Cars/car_<index-de|000,57,1><ext|xExt|xMimeExt|.jpg>`
or
`Cars/car_<index-de|###,57,1><ext|xExt|xMimeExt|.jpg>`

Of course, not suggesting this with any kind of entitlement, just thought about it, and it'd be quite cool. :-) Oh, and the examples above, are purely just me thinking aloud on implementation of the idea.

Still a good extension! Wishing you luck whatever happens. :-)

**Comment by mcdamo** [comment]
Thanks for the suggestion. Selecting the starting index is an interesting feature, though I think I would avoid entering the specific number into a path rule. My goal is for the path rules to be general purpose and so I would look for a method to set this starting index without needing to edit the rules over and again.

**Comment by mcdamo** [comment]
The options to set the starting value and increment value has been included in v4
