### ISSUE TITLE
It never works - always Path rules failed

### ISSUE THREAD

**Issue by mecheng-analyst** [mcdamo/tab-image-saver#46]
I downloaded it. Default everything. Icon shows up, click button on active tab, always get same response. ANY site, ANY image.

**Comment by mcdamo** [comment]
The default path rules should always fall back to a failsafe path like `example.com/img_0001.jpg`

What is your:
- Firefox version
- Test URL
- Path rules (copy and paste from the Preferences page)

**Comment by lawvol** [comment]
I too am experiencing this behavior.  It only started in the last day or so.  Previously it worked flawlessly.  Now it doesn't work on any image url.  I am using the standard path rules.  I am using Firefox 60.8.0esr (32-bit).

**Comment by mcdamo** [comment]
Thanks @lawvol the issue affected Firefox < 67. I released fix now as v2.5.6.

**Comment by lawvol** [comment]
Thanks so much for your work on this.  Best wishes!

**Comment by mcdamo** [comment]
Issue resolved.
