### ISSUE TITLE
Regular Expression don't work as expected

### ISSUE THREAD

**Issue by TomberWolf** [mcdamo/tab-image-saver#47]
Hey,

I can't figure out how to replace all forscores in a tabTitle with an underscore.
Common JavaScript regex don't seem to work.
Could you please give us an example?

**Comment by mcdamo** [comment]
What is 'forscores' ?

**Comment by TomberWolf** [comment]
Argh... damn. Sorry. Auto correction.
Forward slash.

**Comment by mcdamo** [comment]
Another character must be used as the delimiter instead of slash, this example uses `#`.
This will use the tab title and replace all slashes with underscores:
`<tabTitle"#replace#/#_#g"><ext>`
