### ISSUE TITLE
filenames

### ISSUE THREAD

**Issue by charliegc4** [mcdamo/tab-image-saver#49]
Used to save the images with their filenames, now all I get is a random 10 digit numeric name. 

Searched and searched and can't find anywhere to save with original file names.

**Comment by mcdamo** [comment]
This addon does not generate random filenames. It is likely the website you are using has changed the file naming.

**Comment by charliegc4** [comment]
It is weird because I open a bunch of images in new tabs. I can see the image name as the tab name, and if I go to the tab and right-click and save the image, I get the proper name. If I use the addon, I get a random 10 digit number for the name. The biggest issue is that these random names are not sequential, but the photos sometimes are a few different series. After saving 30 or so tabs, the images are all mixed up. ;-(

This addon is the only reason I still use Firefox. Guess I can finally look at other browsers now that I need to save the images manually.
