### ISSUE TITLE
Save all images in a tab

### ISSUE THREAD

**Issue by tonglil** [mcdamo/tab-image-saver#5]
Is there a functionality / related extension that will save all images in a tab (instead of the largest in each tab)?

**Comment by john5698** [comment]
I would second this feature request. I would love it to save all images (meeting the specified min file sizes) that are found in the tab selection which may be current tab, tabs to the left or right of current tab or all tabs (in the current window?).

**Comment by mcdamo** [comment]
There are addons that will save all images in a tab, for example https://addons.mozilla.org/en-US/firefox/addon/save-all-images-webextension/

Sorry, I do not plan to add that feature at this time.

**Comment by mcdamo** [comment]
Try it out in v1.2.0 with option Filter: All images
