### ISSUE TITLE
Active Tab Only?

### ISSUE THREAD

**Issue by urusaiuta** [mcdamo/tab-image-saver#50]
Is there any chance an option for only active tabs for left, right, and all to be downloaded? I work with a lot of tabs, and I would like it if only my 30 active tabs had its images downloaded, not 180 tabs. This causes my Firefox to overload my ram and it freezes.

I would appreciate if you could implement this.

**Comment by mcdamo** [comment]
What is active tabs, how do you tabs to be active?
Have you tried **Advanced option >> Skip discarded tabs** ?
