### ISSUE TITLE
Ability to Set Output Filename & 3-digit Suffix

### ISSUE THREAD

**Issue by SwiftMove** [mcdamo/tab-image-saver#51]
I switched from Firefox to Waterfox back when Mozilla dropped support for Legacy add-on's. I've been using the "Save Images" add-on for years and "Tab Image Saver" is the closest I've found to replace it. However, one feature I didn't see was the ability to set the output filename and use a 3-digit suffix. This is useful in cases where you have several tabs with images, and you want them to be saved from left to right, in the same order as the tabs. 

Example: Tab1=image001, Tab2=image002, Tab3=image003, etc.

Perhaps this is something you'll consider in a future release?

**Comment by mcdamo** [comment]
[Path rules](https://github.com/mcdamo/tab-image-saver#path-rules) option already supports this:

`img_<###index><ext|xExt|xMimeExt|.jpg>` will save files like _img_001.jpg_, in tab order.
