### ISSUE TITLE
Carrying on numeration between download sessions

### ISSUE THREAD

**Issue by eduard93** [mcdamo/tab-image-saver#52]
Let's say I download images from one host, so my images are saved as:
```
<basedir>\<host>\img_001.png
<basedir>\<host>\img_002.png
<basedir>\<host>\img_003.png
<basedir>\<host>\img_004.png
```

Some time passed and I want to download some other images for the same host, currently I have two options:
- overwrite (I lose old images and don't want that)
- rename (`<basedir>\<host>\img_001_(1).png` etc) - this can work, but also breaks image order.

Is it possible to check last image number in folder and start from incrementing that number?
So in the case above where images 001-004 exist, if we start a new download, start it from 005?

I guess I'm proposing adding third option to `Duplicate filename action`: append.

**Comment by mcdamo** [comment]
The option to set the starting value and continue indexing between downloads been included in v4.
