### ISSUE TITLE
Append Tab title to Save Folder

### ISSUE THREAD

**Issue by allstar64** [mcdamo/tab-image-saver#53]
I'm one of those who used to use the old "Save Images" addon which I'm sure you've heard about. My version 28 of firefox finally has stopped working on too many sites to justify continuing to use it so I've been forced to update and look for a replacement and this seems to be a very good alternative. There's just one thing that the old "Save Images" could do that I can't figure out how to replicate. There used to be an option to "Append Tab title to Save Folder." Basically the name of the Subfolder that an image was saved to would be automatically set to the Tab title the image came from. This was convenient since the albums I was downloading from would have the same tab title for all images in the album and I could open multiple albums and when I saved the images the images would be automatically sorted into proper folders for each album without me needing to rename each and every one. This also meant that if images from different albums had the same name (001, 002 ect) this wouldn't cause any conflicts.

When I found your addon I saw the paths options and one of the paths options is for tabTitle but when I tried to use it in the "path" box this only seemed to change the file name, not the sub folder name. Is there a way to replicate this behavior with the tools as is and if not is it something that could be added? Regardless thanks for your work.

**Comment by mcdamo** [comment]
Add a slash between the tabTitle and file name parts like so: `<tabTitle>/<name><ext>`

**Comment by allstar64** [comment]
Ah, well now I just feel silly. Thanks, that works.
