### ISSUE TITLE
Domain specific rules

### ISSUE THREAD

**Issue by EraDKtor** [mcdamo/tab-image-saver#55]
It would be awesome if you could add the option to create domain specific rules. I've got the problem that some image sites use the same image names for multiple galleries (e.g. page numbers or always "index") while others use hashes. Adding the tab title helps but i have to manually change the rule order for some sites because they use tag lists as title (for example) - causing complete chaos. 

Allowing to filter rules by host would help greatly with fine-tuning a proper name-scheme.

Thanks for the great addon!

**Comment by mcdamo** [comment]
I'm working on a major update that will add this feature.

**Comment by mcdamo** [comment]
This feature is now available in v3.0!
