### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by andy-gutsche** [mcdamo/tab-image-saver#6]
**Options:**
#########################
**Default action**
Right of current tab
Include current tab: true
Restrict to image tabs: false

**Dimensions (pixels)**
Min width: 100
Max width: 100

**Duplicate filename action**
Rename (automatic)

**Finished downloading**

Close tabs: true
Hide from download history: false
Show notification popup: true

###########################

**Expected behavior:** Saves the biggest image in each tab right from current tab including current tab to the default download folder and closes the tabs afterwards

**Current behavior:** Popup shows "0 images downloaded", no images saved to download folder, tabs still open

I'm running Firefox Quantum  57.0 (64 Bit) on a Windows 7 Ultimate Version 6.1 (Build 7601: Service Pack 1)

**Comment by Hlsgs** [comment]
+1
It doesn't "see" images that have a parameter after the extension, like ":large" from Twitter or "?oh=" from Facebook as images and therefore ignores those tabs. I wonder if @mcdamo is still actively developing this, as I find it very useful otherwise.

**Comment by mcdamo** [comment]
Please try v1.1.2, there are improvements in filename handling and the notification popup will report the number of tabs skipped or failed downloading.

**Comment by Hlsgs** [comment]
Tested on Facebook and Twitter and it works. Only thing is it doesn't save duplicate tabs if it encounters them(which it should IMO). It just saves the first one encountered and skips the duplicates. I'll keep testing. Thanks!

**Comment by mcdamo** [comment]
It only skips tabs when no images are saved, either if the images are too small or they fail to download.
