### ISSUE TITLE
"tabs do not have permission" error and inconsistent settings

### ISSUE THREAD

**Issue by RagglenLove** [mcdamo/tab-image-saver#60]
I'm running Firefox 78.0.2 (64-bit) on Lubuntu 18.04 on Private Browsing Mode.

I updated to version 3.0.0, I got a "tabs do not have permission" error when I tried to download images from Wikimedia Commons (https://commons.wikimedia.org/).

These are my customized settings: 
**Default action**: Right of current tab
**Browser action**: Default action
**Image filter**: Largest image
**Duplicate filename action**: Rename
**After downloading**: Close tabs, Show notification and Clear download history

I tried to save images from 7 tabs, but I was unable to download the images and the message I got was, "7 tabs do not have permission."

As a test, I downloaded and installed version 2.5.6, and it works, I was able to get the images that I wanted.

Another issue with version 3.0.0 is inconsistent settings, when I set my customized settings and I close and open my browser, my settings vanish.

These issues do not happen with version 2.5.6, so until then, I'm sticking to version 2.5.6.

**Comment by mcdamo** [comment]
There was a bug related to Private Browsing Mode that was breaking some functionality, the issues you describe may have been a side-effect of this.

Please try v3.0.1 and see if it resolves this for you.

**Comment by RagglenLove** [comment]
![2020-07-30-105652_1366x768_scrot](https://user-images.githubusercontent.com/45503845/88875668-3feffe00-d254-11ea-9142-6503c0e63a00.png)

Same issue like before, no change. I didn't notice it before, as you can see in the screenshot of my settings, there's a " ! " on the Global Settings button.

**Comment by mcdamo** [comment]
@RagglenLove the "!" icon on Global Settings should only display if the path rules are empty. Do you have path rules here?

Also the "Download in Private Browsing Mode" setting cannot be selected if the extension hasn't been granted permission to run in private windows. This setting is in the Firefox Add-ons Manager:
![image](https://user-images.githubusercontent.com/9359073/88897157-31bed380-d28e-11ea-85cb-6273b496ac0d.png)

**Comment by RagglenLove** [comment]
![2020-07-30-164807_1366x768_scrot](https://user-images.githubusercontent.com/45503845/88903413-3da69780-d286-11ea-8f39-203a2b469f91.png)

I've checked and it is set to run in Private Browsing Mode.

During the time of the screenshot of the settings, the rules were empty.

Something strange just happened, now it works all of a sudden, I didn't toggle the private browsing mode at all, it just suddenly works.

I don't know what happening here.

**Comment by RagglenLove** [comment]
Looks like it updated and now it works, because it was 3.0.1 a few minutes ago and now it's 3.0.3.
