### ISSUE TITLE
How do I get this add-on to stop taking over my sidebar?

### ISSUE THREAD

**Issue by boogiepop** [mcdamo/tab-image-saver#64]
Pic related. My bookmarks or my history should be in there, not this add-on's goddamn menu

![Untitled](https://user-images.githubusercontent.com/2982588/102020935-a6496900-3d7c-11eb-88ff-4c93a5079811.jpg)
.

**Comment by mcdamo** [comment]
This add-on does not take over the sidebar; bookmarks, history, etc are still there.

![Sidebar](https://user-images.githubusercontent.com/9359073/105286422-59be3c80-5c0a-11eb-8a05-af6fbddb89f5.png)
