### ISSUE TITLE
Images from post attachment in some forum tends to save images as "attachment.php"

### ISSUE THREAD

**Issue by nonjenec** [mcdamo/tab-image-saver#66]
the link looks like this `https://urlurlurlurl.com/attachment.php?aid=123456`. If I start downloading with any option in Tab Image Saver, it would download like usual but it saves as `attachment (1).php`. when I rename it to let's say `picture1.jpg`, the images shows and everything else is fine, like the image size. I think it's because of the link where normally it says `https://urlurlurlurl.com/picture1.jpg` but in this case it was the link above and it confuses the add-on on naming stuff. I could rename it my self but I'd like to keep the name the way it should be.

**Comment by mcdamo** [comment]
Try this path rule:
`<name|xName>.<xExt|xMimeExt|jpg>`
