### ISSUE TITLE
Save without downloading again?

### ISSUE THREAD

**Issue by ravvikiran** [mcdamo/tab-image-saver#71]
Hi,
the addon works fine with saving the images but i noticed that in the process of saving, the addon specifically downloads the image again from image url. can it be possible to just save the image without downloading again?
Thank you.

**Comment by mcdamo** [comment]
Firefox has made security changes that affect how the proxy behaves.

I believe the breaking change was [1681330 - Enable Network Partitioning](https://bugzilla.mozilla.org/show_bug.cgi?id=1681330) released in [Firefox 85](https://www.mozilla.org/en-US/firefox/85.0/releasenotes/).

This security change has the effect that download addons cannot access the cached items from browser windows:
  * [1670278 - Enable extensions to send network requests (fetch) with a specific cookieStoreId (container tab context)](https://bugzilla.mozilla.org/show_bug.cgi?id=1670278)
  * [1691907  - Image downloader extensions fail to use cache with network partitioning enabled, re-download attempts more likely to result in failure](https://bugzilla.mozilla.org/show_bug.cgi?id=1691907)
  * [1698863 - Allow extensions to specify request context in the browser.downloads.download API](https://bugzilla.mozilla.org/show_bug.cgi?id=1698863)

Presently there is a workaround by **disabling** the new security feature in Firefox. Making this change is obviously at your own risk: 
`about:config` → `privacy.partition.network_state` → `false`
