### ISSUE TITLE
Bug - Fails to download all tabs in session.

### ISSUE THREAD

**Issue by Rubber-Duckie** [mcdamo/tab-image-saver#72]
Leaves tabs un-actioned after clicking download all on right button.
Cannot then use the add-on to download those skipped tabs, since the add-on does not seem to be able to see them. As if the enumeration is failing and the add-on is now out of sync with the actual browser tab state.
In this example, it seems to leave 5 tabs un-actioned.

The error is "failed to download" - "503: Service Temporarily Unavailable"

However, there is no issue with the image or its host. Tab refresh works fine, but still the add-on refuses to download it.

Preference is set to "image tabs only"
Same issue when set to "largest image" 

Firefox 95.0.2 (64-bit)

**Comment by mcdamo** [comment]
That error suggests the host is blocking the downloads when they are coming from the addon, so unfortunately I can't debug it without knowing the urls.

As a workaround you might have success by disabling the Firefox security in here: #71

**Comment by mcdamo** [comment]
No response in 2 months, closing.
