### ISSUE TITLE
No longer downloading images from mewe.com...

### ISSUE THREAD

**Issue by pc-maint** [mcdamo/tab-image-saver#77]
It used to work perfectly, but since a recent update, it no longer downloads images from mewe.com
For example, this one:
https://mewe.com/api/v2/photo/i9huw3EioQdZ3vUjfr8gTZdP9zH8aNeA8GCy4BFqCvliL33N1GKnLJcza9w/800x800/img?static=0

Thanks...

Firefox 91.7esr (64-bit)
Tab Image Saver 4.0.7 (updated 14 March 2022)

**Comment by mcdamo** [comment]
URL is inaccessible, cannot test.
