### ISSUE TITLE
addon broken

### ISSUE THREAD

**Issue by nouse1234** [mcdamo/tab-image-saver#78]
Hi,

some weeks ago, the addon started to save images as *._ext_ files. In this process, file names are lost.
The files can be easily saved as images, but its still annoying.

any intentions to fix this, or is this project abandoned?

![Unbenannt](https://user-images.githubusercontent.com/55952439/167798862-27126be5-cc50-408e-9839-218411436543.JPG)

**Comment by mcdamo** [comment]
This is [answered in the FAQ](https://github.com/mcdamo/tab-image-saver#filenames-are-_name__ext_)
