### ISSUE TITLE
Firefox 58 update causes Tab Image Saver to pop-up the File Save Dialog for every file saved

### ISSUE THREAD

**Issue by AJS44** [mcdamo/tab-image-saver#8]
Tab Image Saver was working well with Firefox 57, but after the FF58 update, TIS now is forced to run super-slow as it pops-up the Windows File-Save dialog for each image file that it tries to save.

**Comment by timeceeper** [comment]
yes.. please can you fix it..

**Comment by mcdamo** [comment]
This should be fixed in newly released v1.1.1
