### ISSUE TITLE
Does not work on t.me

### ISSUE THREAD

**Issue by tkzv** [mcdamo/tab-image-saver#85]
The addon doesn't save any images on t.me pages. This may be due to images having names too long for most file systems, images placed in iframes or images being the background. 
Example page: https://t.me/news_kremlin_eng/111

**Comment by mcdamo** [comment]
Telegram appears to use frames and embeds the pictures as background images in CSS. This is beyond the scope of what this addon can support.

**Comment by tkzv** [comment]
Which makes the addon kinda useless.
