### ISSUE TITLE
Cannot save images properly from depop com site.

### ISSUE THREAD

**Issue by estatistics** [mcdamo/tab-image-saver#87]
Cannot save images properly from depop com site.

If you try to save images from this url:  [https://www.depop.com/products/ambergold-90s-brown-embroidered-cargos/](url),
it will save only 1 or 2 images. 

It would be of great help if "name" rules can also apply for paths. 
For example, i have a tab open from user "annete". I would like to save all images under this folder name which appears in "tab name".

**Comment by mcdamo** [comment]
Not an issue with this addon. Use the `${alt}` rule or include an `${index}` number and you might get some unique names.

**Comment by estatistics** [comment]
tab name is "ambergold-90s-brown-embroidered-cargos/" 
1) using "${alt}${index}${host}/img_${index.padStart(3,0)}.${ext||xExt||xMimeExt||"jpg"}" as a rule at Path rules 
i get "Women's Brown Trousers1media-photos.depop.com" which is the title of image and not of the tab.
2) Saves only 1 image while exists multiple images
3) putting path rules in subfolder options "${alt}${index}" i get the folder "${alt}${index}". 

So, you closed this as invalid. Your answer is invalid. 
Thanks anyway for this incredible addon, however a big miss is path rules in subfolder option.

**Comment by mcdamo** [comment]
> tab name is "ambergold-90s-brown-embroidered-cargos/"

1. What you are asking for appears to be part of the tab's url. This is available in the [`${tabPath}` variable](https://github.com/mcdamo/tab-image-saver/#variables)
2. You might have a setting in the Image Filter section of the options that is limiting the saved images.
3. Not an issue, subfolder option is text only. As seen in your example you can create dynamic subfolders using path rules.

**Comment by estatistics** [comment]
See my options
![Selection_114](https://github.com/mcdamo/tab-image-saver/assets/41580704/c7e48b34-bf59-4b9d-a5f4-506d8e66f7fb)

see what downloaded (tabpath worked!:
![Selection_115](https://github.com/mcdamo/tab-image-saver/assets/41580704/31531dc5-9960-45cd-9c81-4e321cf5fe74)
