### ISSUE TITLE
Great Add-on!! (stopped working on March 16th... :-(

### ISSUE THREAD

**Issue by LonjaZurbaran** [mcdamo/tab-image-saver#92]
Incredibly useful and easy to use. I've been using it for months in all of my devices (Windows and Mac) with thousands of downloads. Congratulations for the great work.

But today it has stopped working :-( 

I've tried uninstalling and reinstalling it, and trying all of the Preferences... but seems to be dead. (Doesn't answer at all, no downloads, no messages. Not in private tabs neither public browsing)

Firefox version 115.8 
in OS 10.13.6

**Comment by mcdamo** [comment]
Hi @LonjaZurbaran, which version of the addon is installed?

What is not working, the downloads for a site or the whole addon? If you can access the preferences then it sounds like it is ok.

You could try debug to see if there are any errors reported by the add-on that are causing it to fail: Add-ons / Extensions >> Debug Add-ons >> Inspect (the installed addon)

**Comment by LonjaZurbaran** [comment]
Hi! McDamo.

Thanks a lot for the INCREDIBLY useful add-on. It's really a great job!

The version not working is 4.4. So I managed to downgrade to 4.3 and it
works flawlessly again.

**Comment by mcdamo** [comment]
Any error will be in the Extension console: go to page `about:debugging#/runtime/this-firefox` and Inspect this addon.

**Comment by LonjaZurbaran** [comment]
Back to 4.3 everything goes perfect

(Sorry for my low IT skills, i just survive and your add-on is incredibly
useful for dummies like me)

(We are downloading thousands of pictures per hour for an AI project. We
couldn’t do it without it)

Thaaanks!




Enviado desde dispositivo móvil

**Comment by JeffreySmalley** [comment]
> Any error will be in the Extension console: go to page `about:debugging#/runtime/this-firefox` and Inspect this addon.

here is a full run that results in failure (it is always the same)

running 
Object { windowId: 1, tabId: 771, action: "active" }
[background.js:2:133370](moz-extension://7ca471b4-0c81-4828-bd03-4edf9b7973c8/background.js)
URL queued: https://pbs.twimg.com/media/GK-vS78bsAMEmWJ?format=jpg&name=900x900 [background.js:2:119731](moz-extension://7ca471b4-0c81-4828-bd03-4edf9b7973c8/background.js)
rule: ${index}.${ext}, filename: 113542., valid: false [background.js:2:112585](moz-extension://7ca471b4-0c81-4828-bd03-4edf9b7973c8/background.js)
rule: ${index}.${xExt||xMimeExt}, filename: 113542.jpg, valid: true [background.js:2:112585](moz-extension://7ca471b4-0c81-4828-bd03-4edf9b7973c8/background.js)
createFilename ${index}.${xExt||xMimeExt} 113542.jpg [background.js:2:112719](moz-extension://7ca471b4-0c81-4828-bd03-4edf9b7973c8/background.js)
fetchDownload from Tab(771) 0.003s: pics/113542.jpg [background.js:2:85904](moz-extension://7ca471b4-0c81-4828-bd03-4edf9b7973c8/background.js)
saveDownload(126) from Tab(771): pics/113542.jpg [background.js:2:87174](moz-extension://7ca471b4-0c81-4828-bd03-4edf9b7973c8/background.js)
Download(126) interrupted: E:\Users\Cloud\Downloads\pics\113542.jpg [background.js:2:83104](moz-extension://7ca471b4-0c81-4828-bd03-4edf9b7973c8/background.js)
Window(1) has ended 30 [background.js:2:110289](moz-extension://7ca471b4-0c81-4828-bd03-4edf9b7973c8/background.js)
imagesFailed https://pbs.twimg.com/media/GK-vS78bsAMEmWJ?format=jpg&name=900x900: pics/113542.jpg => undefined [background.js:2:109497](moz-extension://7ca471b4-0c81-4828-bd03-4edf9b7973c8/background.js)
0 Saved, 1 Failed

**Comment by mcdamo** [comment]
I wonder if it is the same as #94 

If you toggle the addon Sidebar, and try to download using the buttons in the Sidebar, does it show why it fails?

**Comment by LonjaZurbaran** [comment]
Thanks. I will try tonight with your instructions.

I use mainly Macintosh with High Sierra and Firefox last version (This
happened in all my 4 macs where I installed). All same configuration.

I'm busy until tonight.

Will try to follow your instructions and will write you back tonight late.

Thanks for your work
daniel

**Comment by LonjaZurbaran** [comment]
Hi. I've checked the newest version (4.5) again in a Mac OS 10.13.6

Firefox version (newest 115.9)

No images downloaded.

I'm sending you a couple of screenshots from my console, in case it can
help.

(Also, I copy and paste the text down here)

Hope this helps

(version 4.3 still working ok)






Loading background options background.js:2:130321
ALLOW_DOWNLOAD_PRIVATE true background.js:2:64517
running
Object { windowId: 930, tabId: 11, action: "active" }
background.js:2:133172
0 Saved, 0 Failed background.js:2:108279
running
Object { windowId: 930, tabId: 11, action: "right" }
background.js:2:133172
Data-URL queued 2 background.js:2:119395
rule: ${name}.${ext}, filename: 2Q==., valid: false background.js:2:112342
createDownloads failed
Object { src:
"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAMAAgADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDrqXFLilxXUeaNxRinYpcUAMxS4p2KXFADMUYp+KXFADMUYp+KXFADMUYp+KXFADMUYp+KXFADMUYp+KMUhjMUuKfijFADMUYqTFGKAGYoxT8UYoEMxS4p+KMUAMxS4p+KMUhDcUU6kzQAClpKr…"
}
Error: Could not establish connection. Receiving end does not exist.
    e moz-extension://edea94c6-4724-45a3-9ffe-9fda7cc15faf/background.js:2
background.js:2:115867
rule: ${name}.${ext}, filename: 2Q==., valid: false background.js:2:112342
createDownloads failed
Object { src:
"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAMAAgADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDx+mNT1pHFdJciFqrHrU8nSq560znkSx06mpTxQCFApFmMM6kVJt+WqVwf3h9qa1G246nQMRLAGX0zVXvUejz7kaJjyORVmRMMcVGzsdDfPFSHW3Eq/WtTbisqPhlPvW5tygb1FRN2Z0YdcyaKj…"
}
Error: Could not establish connection. Receiving end does not exist.
    e moz-extension://edea94c6-4724-45a3-9ffe-9fda7cc15faf/background.js:2
background.js:2:115867
pathsFailed
data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAMAAgADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDrqXFLilxXUeaNxRinYpcUAMxS4p2KXFADMUYp+KXFADMUYp+KXFADMUYp+KXFADMUYp+KXFADMUYp+KMUhjMUuKfijFADMUYqTFGKAGYoxT8UYoEMxS4p+KMUAMxS4p+KMUhDc…
background.js:2:109046
pathsFailed
data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAMAAgADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDx+mNT1pHFdJciFqrHrU8nSq560znkSx06mpTxQCFApFmMM6kVJt+WqVwf3h9qa1G246nQMRLAGX0zVXvUejz7kaJjyORVmRMMcVGzsdDfPFSHW3Eq/WtTbisqPhlPvW5tygb1F…
background.js:2:109046
0 Saved, 0 Failed background.js:2:108279
running
Object { windowId: 930, tabId: 11, action: "right" }
background.js:2:133172
Data-URL queued 2 background.js:2:119395
rule: ${name}.${ext}, filename: 2Q==., valid: false background.js:2:112342
createDownloads failed
Object { src:
"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAMAAgADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDrqXFLilxXUeaNxRinYpcUAMxS4p2KXFADMUYp+KXFADMUYp+KXFADMUYp+KXFADMUYp+KXFADMUYp+KMUhjMUuKfijFADMUYqTFGKAGYoxT8UYoEMxS4p+KMUAMxS4p+KMUhDcUU6kzQAClpKr…"
}
Error: Could not establish connection. Receiving end does not exist.
    e moz-extension://edea94c6-4724-45a3-9ffe-9fda7cc15faf/background.js:2
background.js:2:115867
rule: ${name}.${ext}, filename: 2Q==., valid: false background.js:2:112342
createDownloads failed
Object { src:
"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAMAAgADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDx+mNT1pHFdJciFqrHrU8nSq560znkSx06mpTxQCFApFmMM6kVJt+WqVwf3h9qa1G246nQMRLAGX0zVXvUejz7kaJjyORVmRMMcVGzsdDfPFSHW3Eq/WtTbisqPhlPvW5tygb1FRN2Z0YdcyaKj…"
}
Error: Could not establish connection. Receiving end does not exist.
    e moz-extension://edea94c6-4724-45a3-9ffe-9fda7cc15faf/background.js:2
background.js:2:115867
pathsFailed
data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAMAAgADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDrqXFLilxXUeaNxRinYpcUAMxS4p2KXFADMUYp+KXFADMUYp+KXFADMUYp+KXFADMUYp+KXFADMUYp+KMUhjMUuKfijFADMUYqTFGKAGYoxT8UYoEMxS4p+KMUAMxS4p+KMUhDc…
background.js:2:109046
pathsFailed
data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAMAAgADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDx+mNT1pHFdJciFqrHrU8nSq560znkSx06mpTxQCFApFmMM6kVJt+WqVwf3h9qa1G246nQMRLAGX0zVXvUejz7kaJjyORVmRMMcVGzsdDfPFSHW3Eq/WtTbisqPhlPvW5tygb1F…

**Comment by mcdamo** [comment]
@LonjaZurbaran it appears you have only a single path rule and it cannot generate a filename for the site you are using: `rule: ${name}.${ext}, filename: 2Q==., valid: false`

**Comment by LonjaZurbaran** [comment]
I hope that can help.

Back to Version 4.3 works on all my computers flawlessly. I deactivated the
'auto update' option so everything is fine.

Thanks a lot for your work.
