### ISSUE TITLE
Can/does this work on webms, webp, or gifs

### ISSUE THREAD

**Issue by TLMcNulty** [mcdamo/tab-image-saver#97]
If it should by default I must be operating it incorrectly.

**Comment by mcdamo** [comment]
It works on any image format the browser supports.

**Comment by TLMcNulty** [comment]
I've looked/tried to verify this, but when I have webms or mp4s in a list nothing occurs. Is there a way I can view debug or verbose output while the extension logic is going? @mcdamo
